### ISSUE TITLE
pairingData In Intial Pairing Client Call

### ISSUE THREAD

**Issue by gjames2467** [jeanregisser/mediaremotetv-protocol#1]
@jeanregisser 

I am getting hung up on the initial pairingData bytes on the first step in the pairing process see my progression below:

**CLIENT -> SERVER**
```
type: DEVICE_INFO_MESSAGE
identifier: "4D8BC678-C2A2-48E4-AFEC-40D19EC62B73"
priority: 0
[deviceInfoMessage] {
  uniqueIdentifier: "4D8BC678-C2A2-48E4-AFEC-40D19EC62B73"
  name: "iPhone"
  localizedModelName: "Test IPHONE"
  systemBuildVersion: "14D27"
  applicationBundleIdentifier: "com.apple.TVRemote"
  applicationBundleVersion: "186"
  protocolVersion: 1
}

```
**SERVER --> CLIENT**
```
type: DEVICE_INFO_MESSAGE
identifier: "4D8BC678-C2A2-48E4-AFEC-40D19EC62B73"
priority: 0
[deviceInfoMessage] {
  uniqueIdentifier: "4D8BC678-C2A2-48E4-AFEC-40D19EC62B73"
  name: "BJ city"
  systemBuildVersion: "14W5241c"
  applicationBundleIdentifier: "com.apple.mediaremoted"
  protocolVersion: 1
}

```
After the below request it just hangs and the SERVER does not respond.  I believe it is because i am not entering the right pairingData bytes--what am i supposed to put for the initial "pairingData" bytes?

**CLIENT --> SERVER**
```
type: CRYPTO_PAIRING_MESSAGE
priority: 0
[cryptoPairingMessage] {
  pairingData: "WHAT BYTES DO I PUT HERE"
  status: 0
}
```

**Comment by jeanregisser** [comment]
Hi @gjames2467 

Take a look at https://github.com/postlund/pyatv and specifically https://github.com/postlund/pyatv/blob/master/pyatv/mrp/pairing.py
to see an actual implementation of the pairing process that works.
