### ISSUE TITLE
Apple TV Forcibly closes connection on remote after verification Step.

### ISSUE THREAD

**Issue by JoelKellamUltamation** [jeanregisser/mediaremotetv-protocol#8]
I am finding that the Apple TV is upset with me after Pairing then Verifying correctly with it...

At the end of verifying I receive the correct response from the Apple TV,

type: CRYPTO_PAIRING_MESSAGE
priority: 0
[cryptoPairingMessage] {
  pairingData: "\006\001\004"
  status: 0
}

My implementation does also appear under remote devices as an 'Unknown Device', So Pairing an Verifying is not an issue, but once I send the encrypted SET_CONNECTION_STATE and CLIENT_UPDATES_CONFIG_MESSAGE or any other two messages it forcibly closes the connection on me.
it also does not accept any of the navigation commands I send encrypted but is happy with them not encrypted.

My implementation does also appear under remote devices as an 'Unknown Device'

**Comment by starscodermoh** [comment]
have you complete your project can you please share how to create m3 becuase cloases connection after sending m3 iwith the same response from tv as yours : type: CRYPTO_PAIRING_MESSAGE
priority: 0
[cryptoPairingMessage] {
pairingData: "\006\001\004"
status: 0
}

,,
i get this
